name: run_tests

on:
  push:
    branches:
    tags:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 4.0.0

      # - name: Build
      #   run: bazel build //zetasql/parser:all -c dbg --spawn_strategy=local

      - name: Run analyzer test
        run: bazel test --test_output=all //zetasql/analyzer:container_hash_equals_test

      - name: Run parser test
        run: bazel test --test_output=all //zetasql/parser:parse_tree_errors_test
